# Устаревший атрибут version был удален, Compose будет использовать последнюю спецификацию

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3003:3000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:8.2.2
    container_name: redis
    restart: always
    env_file:
      - .env
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
